// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2KPMSZBPUIYeIfANkBuVXTARjkUxTHDQ',
    appId: '1:639962458163:web:e31336ba5a99e63588db46',
    messagingSenderId: '639962458163',
    projectId: 'riverpod-project-59bb6',
    authDomain: 'riverpod-project-59bb6.firebaseapp.com',
    storageBucket: 'riverpod-project-59bb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc0kRoKgBMfDD-XOnM0tL_kglzdVb1XFc',
    appId: '1:639962458163:android:6df762bc60a5bcd388db46',
    messagingSenderId: '639962458163',
    projectId: 'riverpod-project-59bb6',
    storageBucket: 'riverpod-project-59bb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuqZE9JngZFNDip_DUZu0fQImzOm84VL8',
    appId: '1:639962458163:ios:2464af01b1bf674188db46',
    messagingSenderId: '639962458163',
    projectId: 'riverpod-project-59bb6',
    storageBucket: 'riverpod-project-59bb6.appspot.com',
    iosBundleId: 'com.example.riverpodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuqZE9JngZFNDip_DUZu0fQImzOm84VL8',
    appId: '1:639962458163:ios:7fb43212b843094b88db46',
    messagingSenderId: '639962458163',
    projectId: 'riverpod-project-59bb6',
    storageBucket: 'riverpod-project-59bb6.appspot.com',
    iosBundleId: 'com.example.riverpodapp.RunnerTests',
  );
}
